name: Generate Plot and Update Twitter Banner

on:
  workflow_dispatch:

jobs:
  generate_plot:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      # Set other variables from ENV_FILE
      X_API_KEY: ${{ secrets.X_API_KEY }}
      X_API_SECRET: ${{ secrets.X_API_SECRET }}
      X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
      X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
      X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
      APP_ID: ${{ secrets.APP_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Load environment variables
        run: echo "$(<ENV_FILE)" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("ggplot2", "data.table", "magick", "cowplot"), repos="https://cran.rstudio.com/")'

      - name: Generate Plot and Update Twitter Banner
        run: node index_crypto_banner.js

      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: generated-files
          path: |
            components/plotCoin.csv
            components/Header1500x500.png

      - name: Cleanup
        if: always()
        run: rm -rf node_modules/
