name: Generate Plot and Update Twitter Banner

on:
  workflow_dispatch: # Run manually

jobs:
  generate_plot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Node.js dependencies
        run: |
          npm ci
          npm i

      - name: Load environment variables
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies for magick
        run: |
          sudo apt-get update
          sudo apt-get install -y libmagick++-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("ggplot2", "data.table", "magick", "cowplot"), repos="https://cran.rstudio.com/")'

      - name: Generate Plot and Update Twitter Banner
        run: node index_crypto_banner.js

      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: generated-files
          path: |
            components/plotCoin.csv
            components/Header1500x500.png

      - name: Cleanup
        if: always()
        run: rm -rf node_modules/
